--[[
    Pal Database for PalSpawner
    Complete list of standard Pals with internal names for Palworld v1.0
    Source: Steam community guide, palmods.gg, palworld.wiki.gg
]]

local M = {}

M.pals = {
    {dex=1,   name="Lamball",          internal="SheepBall",          type1="Neutral", type2=""},
    {dex=2,   name="Cattiva",          internal="PinkCat",            type1="Neutral", type2=""},
    {dex=3,   name="Chikipi",          internal="ChickenPal",         type1="Neutral", type2=""},
    {dex=4,   name="Lifmunk",          internal="Carbunclo",          type1="Grass",   type2=""},
    {dex=5,   name="Fuack",            internal="BluePlatypus",       type1="Water",   type2=""},
    {dex="5B",name="Fuack Ignis",      internal="BluePlatypus_Fire",  type1="Fire",    type2="Water"},
    {dex=6,   name="Vixy",             internal="CuteFox",            type1="Neutral", type2=""},
    {dex=7,   name="Celaray",          internal="FlyingManta",        type1="Water",   type2=""},
    {dex="7B",name="Celaray Lux",      internal="FlyingManta_Thunder",type1="Electric",type2="Water"},
    {dex=8,   name="Cremis",           internal="WoolFox",            type1="Neutral", type2=""},
    {dex=9,   name="Croajiro",         internal="KendoFrog",          type1="Water",   type2=""},
    {dex="9B",name="Croajiro Noct",    internal="KendoFrog_Dark",     type1="Dark",    type2="Water"},
    {dex=10,  name="Herbil",           internal="LeafMomonga",        type1="Grass",   type2=""},
    {dex=11,  name="Teafant",          internal="Ganesha",            type1="Water",   type2=""},
    {dex=12,  name="Gumoss",           internal="PlantSlime",         type1="Grass",   type2=""},
    {dex=13,  name="Pupperai",         internal="SamuraiDog",         type1="Neutral", type2=""},
    {dex=14,  name="Clovee",           internal="CloverFairy",        type1="Grass",   type2=""},
    {dex=15,  name="Jolthog",          internal="Hedgehog",           type1="Electric",type2=""},
    {dex="15B",name="Jolthog Cryst",   internal="Hedgehog_Ice",       type1="Ice",     type2="Electric"},
    {dex=16,  name="Depresso",         internal="NegativeKoala",      type1="Neutral", type2=""},
    {dex=17,  name="Pengullet",        internal="Penguin",            type1="Water",   type2="Neutral"},
    {dex="17B",name="Pengullet Lux",   internal="Penguin_Electric",   type1="Electric",type2="Water"},
    {dex=18,  name="Penking",          internal="CaptainPenguin",     type1="Water",   type2="Ice"},
    {dex="18B",name="Penking Lux",     internal="CaptainPenguin_Black",type1="Dark",   type2="Water"},
    {dex=19,  name="Hoocrates",        internal="WizardOwl",          type1="Dark",    type2=""},
    {dex=20,  name="Melpaca",          internal="Alpaca",             type1="Neutral", type2=""},
    {dex=21,  name="Kingpaca",         internal="KingAlpaca",         type1="Neutral", type2=""},
    {dex="21B",name="Kingpaca Cryst",  internal="KingAlpaca_Ice",     type1="Ice",     type2="Neutral"},
    {dex=22,  name="Daedream",         internal="DreamDemon",         type1="Dark",    type2=""},
    {dex=23,  name="Tanzee",           internal="Monkey",             type1="Grass",   type2=""},
    {dex="23B",name="Tanzee Ignis",    internal="Monkey_Fire",        type1="Fire",    type2="Grass"},
    {dex=24,  name="Nox",              internal="NightFox",           type1="Dark",    type2=""},
    {dex=25,  name="Flambelle",        internal="LavaGirl",           type1="Fire",    type2=""},
    {dex=26,  name="Rooby",            internal="FlameBambi",         type1="Fire",    type2=""},
    {dex=27,  name="Mau",              internal="Bastet",             type1="Dark",    type2=""},
    {dex="27B",name="Mau Cryst",       internal="Bastet_Ice",         type1="Ice",     type2="Dark"},
    {dex=28,  name="Rushoar",          internal="Boar",               type1="Ground",  type2=""},
    {dex=29,  name="Foxparks",         internal="Kitsunebi",          type1="Fire",    type2=""},
    {dex="29B",name="Foxparks Cryst",  internal="Kitsunebi_Ice",      type1="Ice",     type2="Fire"},
    {dex=30,  name="Killamari",        internal="NegativeOctopus",    type1="Dark",    type2=""},
    {dex="30B",name="Killamari Primo", internal="NegativeOctopus_Neutral",type1="Neutral",type2="Dark"},
    {dex=31,  name="Fuddler",          internal="CuteMole",           type1="Ground",  type2=""},
    {dex=32,  name="Eikthyrdeer",      internal="Deer",               type1="Neutral", type2=""},
    {dex="32B",name="Eikthyrdeer Terra",internal="Deer_Ground",       type1="Ground",  type2="Neutral"},
    {dex=33,  name="Direhowl",         internal="Garm",               type1="Neutral", type2=""},
    {dex=34,  name="Caprity",          internal="BerryGoat",          type1="Grass",   type2=""},
    {dex="34B",name="Caprity Noct",    internal="BerryGoat_Dark",     type1="Dark",    type2="Grass"},
    {dex=35,  name="Swee",             internal="MopBaby",            type1="Neutral", type2=""},
    {dex=36,  name="Sweepa",           internal="MopKing",            type1="Grass",   type2=""},
    {dex=37,  name="Turtacle",         internal="TentacleTurtle",     type1="Water",   type2=""},
    {dex="37B",name="Turtacle Terra",  internal="TentacleTurtle_Ground",type1="Ground",type2="Water"},
    {dex=38,  name="Hangyu",           internal="WindChimes",         type1="Ground",  type2=""},
    {dex="38B",name="Hangyu Cryst",    internal="WindChimes_Ice",     type1="Ground",  type2="Ice"},
    {dex=39,  name="Woolipop",         internal="SweetsSheep",        type1="Neutral", type2=""},
    {dex="39B",name="Woolipop Terra",  internal="SweetsSheep_Ground", type1="Ground",  type2="Neutral"},
    {dex=40,  name="Mozzarina",        internal="CowPal",             type1="Neutral", type2=""},
    {dex=41,  name="Azurobe",          internal="BlueDragon",         type1="Water",   type2="Dragon"},
    {dex="41B",name="Azurobe Cryst",   internal="BlueDragon_Ice",     type1="Ice",     type2="Water"},
    {dex=42,  name="Sparkit",          internal="ElecCat",            type1="Electric",type2=""},
    {dex=43,  name="Kelpsea",          internal="Kelpie",             type1="Water",   type2=""},
    {dex="43B",name="Kelpsea Ignis",   internal="Kelpie_Fire",        type1="Fire",    type2="Water"},
    {dex=44,  name="Ribbuny",          internal="PinkRabbit",         type1="Neutral", type2=""},
    {dex="44B",name="Ribbuny Botan",   internal="PinkRabbit_Grass",   type1="Grass",   type2="Neutral"},
    {dex=45,  name="Jelliette",        internal="JellyfishFairy",     type1="Water",   type2=""},
    {dex=46,  name="Jelroy",           internal="JellyfishGhost",     type1="Water",   type2=""},
    {dex=47,  name="Amione",           internal="ClioneTwins",        type1="Ice",     type2="Water"},
    {dex=48,  name="Gloopie",          internal="OctopusGirl",        type1="Water",   type2=""},
    {dex="48B",name="Gloopie Primo",   internal="OctopusGirl_Neutral",type1="Neutral", type2="Water"},
    {dex=49,  name="Galeclaw",         internal="Eagle",              type1="Neutral", type2=""},
    {dex=50,  name="Wispaw",           internal="GhostBlackCat",      type1="Dark",    type2=""},
    {dex=51,  name="Nitewing",         internal="HawkBird",           type1="Neutral", type2=""},
    {dex=52,  name="Tombat",           internal="CatBat",             type1="Dark",    type2=""},
    {dex=53,  name="Tocotoco",         internal="ColorfulBird",       type1="Neutral", type2=""},
    {dex=54,  name="Univolt",          internal="Kirin",              type1="Electric",type2=""},
    {dex="54B",name="Univolt Cryst",   internal="Kirin_Ice",          type1="Ice",     type2="Electric"},
    {dex=55,  name="Gobfin",           internal="SharkKid",           type1="Water",   type2=""},
    {dex="55B",name="Gobfin Ignis",    internal="SharkKid_Fire",      type1="Fire",    type2="Water"},
    {dex=56,  name="Loupmoon",         internal="Werewolf",           type1="Dark",    type2=""},
    {dex="56B",name="Loupmoon Cryst",  internal="Werewolf_Ice",       type1="Ice",     type2="Dark"},
    {dex=57,  name="Cawgnito",         internal="DarkCrow",           type1="Neutral", type2=""},
    {dex=58,  name="Arsox",            internal="FlameBuffalo",       type1="Fire",    type2=""},
    {dex=59,  name="Muffly",           internal="FluffyBird",         type1="Neutral", type2=""},
    {dex=60,  name="Bristla",          internal="LittleBriarRose",    type1="Grass",   type2=""},
    {dex=61,  name="Cinnamoth",        internal="CuteButterfly",      type1="Grass",   type2=""},
    {dex=62,  name="Puffolt",          internal="ElecPomeranian",     type1="Electric",type2=""},
    {dex=63,  name="Elphidran",        internal="FairyDragon",        type1="Dragon",  type2=""},
    {dex="63B",name="Elphidran Aqua",  internal="FairyDragon_Water",  type1="Dragon",  type2="Water"},
    {dex=64,  name="Vanwyrm",          internal="BirdDragon",         type1="Fire",    type2="Dragon"},
    {dex="64B",name="Vanwyrm Cryst",   internal="BirdDragon_Ice",     type1="Ice",     type2="Dragon"},
    {dex=65,  name="Felbat",           internal="CatVampire",         type1="Dark",    type2=""},
    {dex=66,  name="Vaelet",           internal="VioletFairy",        type1="Grass",   type2=""},
    {dex=67,  name="Beegarde",         internal="SoldierBee",         type1="Grass",   type2=""},
    {dex=68,  name="Elizabee",         internal="QueenBee",           type1="Grass",   type2=""},
    {dex=69,  name="Lovander",         internal="PinkLizard",         type1="Neutral", type2=""},
    {dex=70,  name="Grintale",         internal="NaughtyCat",         type1="Neutral", type2=""},
    {dex=71,  name="Tarantriss",       internal="PurpleSpider",       type1="Ground",  type2=""},
    {dex=72,  name="Polapup",          internal="IceSeal",            type1="Ice",     type2=""},
    {dex="72B",name="Polapup Terra",   internal="IceSeal_Ground",     type1="Ground",  type2="Ice"},
    {dex=73,  name="Leezpunk",         internal="LizardMan",          type1="Dark",    type2=""},
    {dex="73B",name="Leezpunk Ignis",  internal="LizardMan_Fire",     type1="Fire",    type2="Dark"},
    {dex=74,  name="Gorirat",          internal="Gorilla",            type1="Grass",   type2=""},
    {dex="74B",name="Gorirat Terra",   internal="Gorilla_Ground",     type1="Ground",  type2="Grass"},
    {dex=75,  name="Surfent",          internal="Serpent",            type1="Water",   type2="Ground"},
    {dex="75B",name="Surfent Terra",   internal="Serpent_Ground",     type1="Ground",  type2="Water"},
    {dex=76,  name="Robinquill",       internal="RobinHood",          type1="Grass",   type2=""},
    {dex="76B",name="Robinquill Terra",internal="RobinHood_Ground",   type1="Ground",  type2="Grass"},
    {dex=77,  name="Flopie",           internal="FlowerRabbit",       type1="Grass",   type2=""},
    {dex=78,  name="Wixen",            internal="FoxMage",            type1="Fire",    type2=""},
    {dex="78B",name="Wixen Noct",      internal="FoxMage_Dark",       type1="Dark",    type2="Fire"},
    {dex=79,  name="Katress",          internal="CatMage",            type1="Dark",    type2=""},
    {dex="79B",name="Katress Ignis",   internal="CatMage_Fire",       type1="Fire",    type2="Dark"},
    {dex=80,  name="Helzephyr",        internal="HadesBird",          type1="Dark",    type2=""},
    {dex="80B",name="Helzephyr Lux",   internal="HadesBird_Electric", type1="Electric",type2="Dark"},
    {dex=81,  name="Elgrove",          internal="GrassMinotaur",      type1="Grass",   type2=""},
    {dex="81B",name="Elgrove Cryst",   internal="GrassMinotaur_Ice",  type1="Ice",     type2="Grass"},
    {dex=82,  name="Lunaris",          internal="Mutant",             type1="Neutral", type2=""},
    {dex=83,  name="Fenglope",         internal="FengyunDeeper",      type1="Neutral", type2=""},
    {dex="83B",name="Fenglope Lux",    internal="FengyunDeeper_Electric",type1="Electric",type2="Neutral"},
    {dex=84,  name="Dinossom",         internal="FlowerDinosaur",     type1="Grass",   type2="Dragon"},
    {dex="84B",name="Dinossom Terra",  internal="FlowerDinosaur_Ground",type1="Ground",type2="Dragon"},
    {dex=85,  name="Mossanda",         internal="Gorilla",            type1="Grass",   type2=""},
    {dex="85B",name="Mossanda Lux",    internal="Gorilla_Electric",   type1="Electric",type2="Grass"},
    {dex=86,  name="Bushi",            internal="Samurai",            type1="Fire",    type2=""},
    {dex=87,  name="Suzaku",           internal="RedDragon",          type1="Fire",    type2=""},
    {dex="87B",name="Suzaku Aqua",     internal="RedDragon_Water",    type1="Water",   type2="Fire"},
    {dex=88,  name="Reptyro",          internal="FireTurtle",         type1="Fire",    type2="Ground"},
    {dex="88B",name="Reptyro Cryst",   internal="FireTurtle_Ice",     type1="Ice",     type2="Ground"},
    {dex=89,  name="Relaxaurus",       internal="LazyDragon",         type1="Dragon",  type2="Water"},
    {dex="89B",name="Relaxaurus Lux",  internal="LazyDragon_Electric",type1="Electric",type2="Dragon"},
    {dex=90,  name="Grizzbolt",        internal="ElecPanda",          type1="Electric",type2=""},
    {dex=91,  name="Digtoise",         internal="DrillTurtle",        type1="Ground",  type2=""},
    {dex=92,  name="Frostallion",      internal="IceHorse",           type1="Ice",     type2=""},
    {dex="92B",name="Frostallion Noct",internal="IceHorse_Dark",      type1="Dark",    type2="Ice"},
    {dex=93,  name="Mammorest",        internal="Elephant",           type1="Ground",  type2=""},
    {dex="93B",name="Mammorest Cryst", internal="Elephant_Ice",       type1="Ground",  type2="Ice"},
    {dex=94,  name="Chillet",          internal="IceDragon",          type1="Dragon",  type2="Ice"},
    {dex="94B",name="Chillet Terra",   internal="IceDragon_Ground",   type1="Dragon",  type2="Ground"},
    {dex=95,  name="Wumpo",            internal="SnowMonkey",         type1="Ice",     type2=""},
    {dex="95B",name="Wumpo Botan",     internal="SnowMonkey_Grass",   type1="Grass",   type2="Ice"},
    {dex=96,  name="Anubis",           internal="Anubis",             type1="Ground",  type2=""},
    {dex=97,  name="Quivern",          internal="FeatherDragon",      type1="Dragon",  type2=""},
    {dex="97B",name="Quivern Botan",   internal="FeatherDragon_Grass",type1="Dragon",  type2="Grass"},
    {dex=98,  name="Jormuntide",       internal="SeaDragon",          type1="Dragon",  type2="Water"},
    {dex="98B",name="Jormuntide Ignis",internal="SeaDragon_Fire",     type1="Dragon",  type2="Fire"},
    {dex=99,  name="Lyleen",           internal="FlowerQueen",        type1="Grass",   type2=""},
    {dex="99B",name="Lyleen Noct",     internal="FlowerQueen_Dark",   type1="Dark",    type2="Grass"},
    {dex=100, name="Blazamut",         internal="FireBahamut",        type1="Fire",    type2=""},
    {dex=101, name="Blazamut Ryu",     internal="FireBahamut_Dragon", type1="Fire",    type2="Dragon"},
    {dex=102, name="Astegon",          internal="DarkDragon",         type1="Dragon",  type2="Dark"},
    {dex=103, name="Menasting",        internal="DarkScorpion",       type1="Dark",    type2="Ground"},
    {dex="103B",name="Menasting Terra",internal="DarkScorpion_Ground",type1="Ground",  type2="Dark"},
    {dex=104, name="Shadowbeak",       internal="BlackGriffon",       type1="Dark",    type2=""},
    {dex=105, name="Paladius",         internal="WhiteKnight",        type1="Neutral", type2=""},
    {dex=106, name="Necromus",         internal="BlackKnight",        type1="Neutral", type2="Dark"},
    {dex=107, name="Jetragon",         internal="JetDragon",          type1="Dragon",  type2=""},
    {dex=108, name="Kitsun",           internal="NineTail",           type1="Fire",    type2=""},
    {dex=109, name="Cryolinx",         internal="IceLion",            type1="Ice",     type2=""},
    {dex="109B",name="Cryolinx Terra", internal="IceLion_Ground",     type1="Ground",  type2="Ice"},
    {dex=110, name="Foxcicle",         internal="IceFox",             type1="Ice",     type2=""},
    {dex=111, name="Reindrix",         internal="IceDeer",            type1="Ice",     type2=""},
    {dex=112, name="Warsect",          internal="Beetle",             type1="Ground",  type2="Grass"},
    {dex="112B",name="Warsect Terra",  internal="Beetle_Ground",      type1="Ground",  type2=""},
    {dex=113, name="Incineram",        internal="FireDevil",          type1="Fire",    type2="Dark"},
    {dex="113B",name="Incineram Noct", internal="FireDevil_Dark",     type1="Dark",    type2="Fire"},
    {dex=114, name="Pyrin",            internal="FireHorse",          type1="Fire",    type2=""},
    {dex="114B",name="Pyrin Noct",     internal="FireHorse_Dark",     type1="Dark",    type2="Fire"},
    {dex=115, name="Nightingale",      internal="BlackBird",          type1="Neutral", type2=""},
    {dex=116, name="Knolem",           internal="Golem",              type1="Ground",  type2=""},
    {dex=117, name="Gildane",          internal="GoldBeast",          type1="Neutral", type2=""},
    {dex=118, name="Selyne",           internal="MoonGoddess",        type1="Neutral", type2=""},
    {dex=119, name="Boltmane",         internal="ElecLion",           type1="Electric",type2=""},
    {dex=120, name="Dazzi",            internal="ThunderBird",        type1="Electric",type2=""},
    {dex=121, name="Beakon",           internal="ThunderEagle",       type1="Electric",type2="Dragon"},
    {dex=122, name="Ragnahawk",        internal="FireEagle",          type1="Fire",    type2="Dragon"},
    {dex=123, name="Kelpsea Ignis",    internal="Kelpie_Fire",        type1="Fire",    type2="Water"},
    {dex=124, name="Frostallion",      internal="IceHorse",           type1="Ice",     type2=""},
    {dex=125, name="Dragostrophe",     internal="DarkDragon2",        type1="Dark",    type2="Dragon"},
    {dex=126, name="Faleris",          internal="FireEagle2",         type1="Fire",    type2=""},
    {dex=127, name="Selyne",           internal="MoonGoddess",        type1="Neutral", type2=""},
    {dex=128, name="Nyafia",           internal="BadCatgirl",         type1="Neutral", type2=""},
    {dex=129, name="Prunelia",         internal="BlueberryFairy",     type1="Grass",   type2=""},
}

return M
